# Generated by Django 5.1.5 on 2025-02-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TableModel',
            new_name='MenuItem',
        ),
    ]
